name = "cf-worker-ws-dev"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "ddc714d3-e21c-496d-b1b6-3bb9a6c6ea15"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
